### ISSUE TITLE
QMK Firmware location

### ISSUE THREAD

**Issue by marhalloweenvt** [Durburz/interphase-firmware#5]
Dear @Durburz ,

I am really fond with your interphase work. And i really want to make one for my own. The problem is i want to make some change in keymap. Maybe i haven't searched enough for your qmk interphase location. So could you point it out for me?
Beside that, i want to make a bigger keyboard like 8*5 per half. Is it possible? If yes, can you point me what i have to modify?
Thanks in advanced.

Regards,

**Comment by Durburz** [comment]
Hey,
thanks. The qmk keymap is in another repository which can be found here: https://github.com/Durburz/qmk_firmware/blob/interphase/keyboards/interphase/keymaps/default/keymap.c
For a bigger layout you would need to modify the firmware for the sender, receiver and qmk. 
Maybe I can give you some further tips these days, when I've got more time.

**Comment by marhalloweenvt** [comment]
Yes, thank you for your reply.
With the receiver pcb, it still use the same one in mitosis repository, right? I plan to other some of them on oshpark.
I am always here, waiting for your tips.
Once again, thank you @Durburz  very much.

Regards,

**Comment by Durburz** [comment]
Yes, the receiver PCB is the same.

Greetings, Durburz

**Comment by marhalloweenvt** [comment]
Thank @Durburz .
I will other them on oshpark right away.
Btw, i will try to point out what different between your interphase-firmware and mitosis-firmware. If i have some difficulties or not understand, please help me to figure them out.
Thanks again in advanced

**Comment by marhalloweenvt** [comment]
Dear @Durburz ,
My layout i want to make is 8*5 per half. I start to modify qmk first. You can check it out [here](https://github.com/marhalloweenvt/qmk_firmware/tree/interphase/keyboards/interphase).
Below are some change that i has make so far base on your wonderful interphase qmk firmware:

+ config.h
`#define MATRIX_ROWS 5`
`#define MATRIX_COLS 16`

+ matrix.c

```
    if (uart_data[10] == 0xE0)
    {
        //shifting and transferring the keystates to the QMK matrix variable
        for (uint8_t i = 0; i < MATRIX_ROWS; i++) {
            matrix[i] = (uint16_t) uart_data[i*2] | (uint16_t) uart_data[i*2+1] << 8;
        }
    }
```

+ Modify for layout in keymap.c and interphase.c. interphase.h

Is there anything i need to modify with the qmk firmware?
Thanks in advanced

**Comment by marhalloweenvt** [comment]
Hello @Durburz ,
Recently, i have just worked around with your sender, receiver firmwares. If you have time, please have a look in this [link](https://github.com/marhalloweenvt/interphase-firmware) and give me some advises or fix me if there is something wrong.
With receiver firmware, i have lots of confuse with these lines:

```
#define BYTE_TO_BINARY_PATTERN "%c%c%c%c%c%c%c%c"
#define BYTE_TO_BINARY(byte)  \
  (byte & 0x80 ? '#' : '.'), \
  (byte & 0x40 ? '#' : '.'), \
  (byte & 0x20 ? '#' : '.'), \
  (byte & 0x10 ? '#' : '.'), \
  (byte & 0x08 ? '#' : '.'), \
  (byte & 0x04 ? '#' : '.'), \
  (byte & 0x02 ? '#' : '.'), \
  (byte & 0x01 ? '#' : '.')
```

If i have a bigger layout, do i need to modify those lines?

Thanks in advanced.

**Comment by marhalloweenvt** [comment]
Hello, it's me, waiting for you <3

**Comment by Durburz** [comment]
Sorry for the late reply ;)
Your changes are looking pretty good so far.
The cited lines with "BYTE_TO_BINARY" are for debugging with a serial terminal only and should work this way without further changes.

Did you already test your changes?

**Comment by marhalloweenvt** [comment]
Thanks for your reply, @Durburz 
I haven't had a change to test this. Receiver pcbs are coming from oshpark and other components like st-link v2 mini programmer, resistor array, are shipping from aliexpress. 
I will feedback to you as soon as i receive them.

**Comment by Durburz** [comment]
@marhalloweenvt are there any news?

**Comment by marhalloweenvt** [comment]
Hello @Durburz ,

Sorry for being silence in such a long time. Recently, there are too much things happen to me in my life from bad to worse. But beside that, there are also pretty much news and most of theme are bad. I have just come back from my business trip last week.
Because of my f__king idiot mobile carrier changed header of our mobile phone (from 0162 to 032), that i had missed my Mitosis receiver PCBs package just because they can contact with me via my mobile phone number (By the time they had changed the number, i was on a business trip in Singapore for a month , that's why i can do the paper work to change my number in that time). And now i have to re-order them again on OSH pack and wait for another 1 month. That's really bug me.

My YJ-14015 bluetooth modules have just arrived yesterday. Seller from Alixpress had forgotten to ship my order for a long time, until i came back from business trip and complained. They said they are sorry and give me 1 more module for apology. Yayyyyyy now i have 4 of them.
For now, i just have 4 modules and 1 Clone ST-Link mini programer from Aliexpress. I still have to wait for receiver PCBs (F__k the mobile carrier).

Have you seen Galzai recently work with ESP32? I think it's really amazing. More convenient than Mitosis in some way. https://github.com/Galzai/MK32

Anyway, i will comeback with your project as soon as possible.

Cheer,
marhalloweenvt

**Comment by marhalloweenvt** [comment]
Hello, it's me.
So after taking a break for a few days, i decided to handwire my prototype keyboard (i get boring when do nothing, still have some day off left after business trip)
I have some confused with the power source. I will use Lithium 3.7V 3000mAH Li-963760 go with TP4056 1A Li-Ion Lithium Battery Charging Module. Follow Core51822 (B) Specifications, it's Operating voltage is 2.0V ~ 3.6V. Mine power source are 3.7V. So do i need to have some kind of component to reduce voltage? Do i need some thing like Si2302 mosfets or MCP1640 to protect Core51822?
Do you have some suggestion for my power source?
Many thanks.

**Comment by Durburz** [comment]
As the voltage of lithium batteries can be over 4V when fully charged, I would strongly recommend a voltage regulator. So far I'm pretty happy with the MCP1640 as it draws very low power. But then you won't have some sort of undervoltage protection for your lithium cell. I planned this feature myself using the nrf51822's ADC-pin.

**Comment by marhalloweenvt** [comment]
Hi,

I have considered about this problem so far. In my country, i have 0% to get a MCP1640. And i have placed order on AliExpress but it takes me over 45 days @@. So i have a solution while waiting for MCP1640 arrive. With the battery charger module TP4056 v2 (which can protect battery when voltage drops at certain point (1.7V or around this) and it’s very easy to find in my local store), i will connect with a AMS1117-3.3V to make sure the output voltage is 3.3V. I haven’t tested my solution yet. It’s just come up in ny mind a few days after I burned a Core (so sad, but I learned a lesson through this experience. Yayyy)

**Comment by marhalloweenvt** [comment]
Hey @Durburz ,

I have successful tested my prototype. So i move on to make PCBs. Designing phase is completed. You can have a look here (sorry for the logo, it is my team Logo)

![45616118_2077942575596136_3851328892656680960_n](https://user-images.githubusercontent.com/23198869/48038495-76920500-e1a3-11e8-8991-d683404a1246.png)

I just want to ask that Could you give me permission to credit you and add your Github link on my PCBs?

Many thanks,

**Comment by Durburz** [comment]
Hey,

The image quality is pretty bad to recognise the logo but I can guess what it's about ;)
For sure you may add a github link.

**Comment by marhalloweenvt** [comment]
Hi,
Thanks. I will add those information on my PCBs.
Have you plan to implementation Bluetooth option like joric did with his metosis? It's quiet cool function.
